# Board: Generic ESP32 Board (Generic)
# Definition: definitions/boards/generic-esp32/manifest.yaml

esphome:
  name: livingroom-rf-ir-remote
  friendly_name: livingroom-rf-ir-remote

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    
logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password
    
# web_server:
#   port: 80
   
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: livingroom-rf-i Fallback Hotspot
    password: !secret wifi_password

captive_portal:

# --- LED EN KNOP ---

# Blauwe status LED (LedLink op GPIO27)
light:
  - platform: binary
    name: "Status LED"
    output: led_output
    id: status_led

output:
  - platform: gpio
    pin: GPIO27
    id: led_output

# Fysieke knop op de behuizing (Button 1 op GPIO0)
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode: INPUT_PULLUP
      ignore_strapping_warning: true 
    name: "Fysieke Knop"

text_sensor:
  - platform: template
    name: "Pronto IR last"
    id: pronto_ir_last
    update_interval: never
  - platform: template
    name: "RC switch RF last"
    id: rc_switch_rf_last
    update_interval: never
    
# --- RF & IR ONTVANGERS ---
remote_receiver:
  # IR Ontvanger (IRRecv op GPIO33)
  - pin:
      number: GPIO33
      inverted: true
    filter: 50us
    idle: 25ms
    id: ir_rx

    on_pronto:
      then:
        - lambda: |-
            id(pronto_ir_last).publish_state(std::to_string(x.data));
    
    dump: all
    # - pronto      # Print remote code in Pronto form. Useful for using arbitrary protocols.
    # - raw         # Print all remote codes in their raw form. Also useful for using arbitrary protocols.
    # - rc5         # Decode and dump RC5 IR codes.
    # - rc6         # Decode and dump RC6 IR codes.
    # - nec         # Decode and dump NEC infrared codes.
    # - panasonic   # Decode and dump Panasonic infrared codes.
    # - sony        # Decode and dump Sony infrared codes.
    # - samsung     # Decode and dump Samsung infrared codes.
    # - samsung36   # Decode and dump Samsung36 infrared codes.
    # - abbwelcome  # Decode and dump ABB-Welcome codes. Messages are sent via copper wires. See transmitter description for more details.
    # - aeha        # Decode and dump AEHA infrared codes.
    # - beo4        # Decode and dump B&O Beo4 infrared codes.
    # - canalsat    # Decode and dump CanalSat infrared codes.
    # - canalsatld  # Decode and dump CanalSatLD infrared codes.
    # - coolix      # Decode and dump Coolix infrared codes.
    # - dish        # Decode and dump Dish infrared codes.
    # - dyson       # Decode and dump Dyson Cool AM7 tower fan codes.
    # - jvc         # Decode and dump JVC infrared codes.
    # - gobox       # Decode and dump Go-Box infrared codes.
    # - haier       # Decode and dump Haier infrared codes.
    # - lg          # Decode and dump LG infrared codes.
    # - magiquest   # Decode and dump MagiQuest wand infrared codes.
    # - midea       # Decode and dump Midea infrared codes.
    # - nexa        # Decode and dump Nexa (RF) codes.
    # - pioneer     # Decode and dump Pioneer infrared codes.
    # - roomba      # Decode and dump Roomba infrared codes.
    # - symphony    # Decode and dump Symphony infrared codes.
    # - toshiba_ac  # Decode and dump Toshiba AC infrared codes.
    # - mirage      # Decode and dump Mirage infrared codes.
    # - toto        # Decode and dump Toto infrared codes.

    
  # 433MHz RF Ontvanger (RFRecv op GPIO19)
  - pin:
      number: GPIO19
    filter: 150us
    tolerance: 30%
    idle: 4ms
    id: rf_rx

    on_rc_switch:
      then:
        - lambda: |-
            id(rc_switch_rf_last).publish_state(std::to_string(x.code));
  
    dump:
      # - raw           # Print all remote codes in their raw form. Also useful for using arbitrary protocols.
      - rc_switch     # Decode and dump RCSwitch RF codes.
      - brennenstuhl  # Decode and dump brennenstuhl RF codes.
      - byronsx       # Decode and dump Byron SX doorbell RF codes.
      - dooya         # Decode and dump Dooya RF codes.
      - drayton       # Decode and dump Drayton Digistat RF codes.
      - dyson         # Decode and dump Dyson Cool AM7 tower fan codes.
      - keeloq        # Decode and dump KeeLoq RF codes.
      - nexa          # Decode and dump Nexa (RF) codes.


    
# --- RF & IR ZENDERS ---
remote_transmitter:
  # IR Zender (IRSend op GPIO25)
  - pin: GPIO25
    non_blocking: true  # <-- Voeg dit toe om de waarschuwing te stoppen
    carrier_duty_percent: 50%
    id: ir_tx

  # 433MHz RF Zender (RFSend op GPIO18)
  - pin: GPIO18
    non_blocking: true  # <-- Voeg dit toe om de waarschuwing te stoppen
    carrier_duty_percent: 100%
    id: rf_tx